In [1]:
import pandas as pd

In [22]:
df = pd.read_csv("/content/Downtown_Parking_Lots (1).csv")

In [23]:
df.head()

,OBJECTID,FACILITYID,INTID,SALESFORCEID,SUBTYPEID,NAME,ADDRESS,OWNERSHIP,TOTALSPACECOUNT,EVSPACECOUNT,...,PARKINGTYPE,NUMBEROFLEVELS,PERMITS,BIPLEASE,BIPAREA,CREATIONDATE,LASTUPDATE,NOTES,SHAPE_Length,SHAPE_Area
0,2,2,2,0.0,0.0,SJ State University 7th Street,,SJSU Parking,1980.0,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,2021/06/23 00:08:34+00,none,1434.256565,123290.02960
1,4,4,4,0.0,0.0,SJ State University 10th Street Garage,,SJSU Parking,1490.0,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,2021/06/23 00:08:34+00,none,1584.074221,132667.95220
2,5,5,5,0.0,0.0,Cahill Lot 4 (Caltrain 4),"4 Cahill Street, San Jose, CA",City of San Jose,149.0,NaN,...,Lot,NaN,0.0,0.0,0.0,0.0,2021/06/23 00:08:34+00,none,936.989709,54333.35930
3,6,6,6,0.0,0.0,Cahill Lot 2 (Caltrain 2),"21 Cahill Street, San Jose, CA",City of San Jose,162.0,NaN,...,Lot,NaN,0.0,0.0,0.0,0.0,2021/06/23 00:08:34+00,none,947.398405,55899.87649
4,7,7,7,0.0,NaN,Cahill Lot 3 (Caltrain 3),71 Cahill Street,City of San Jose,90.0,NaN,...,Lot,NaN,0.0,0.0,0.0,0.0,2021/06/23 00:08:34+00,none,778.829121,37121.44225

In [24]:
df.columns

Index(['OBJECTID', 'FACILITYID', 'INTID', 'SALESFORCEID', 'SUBTYPEID', 'NAME',
       'ADDRESS', 'OWNERSHIP', 'TOTALSPACECOUNT', 'EVSPACECOUNT',
       'ADASPACECOUNT', 'RESERVEDSPACECOUNT', 'VALIDATION', 'PARKINGTYPE',
       'NUMBEROFLEVELS', 'PERMITS', 'BIPLEASE', 'BIPAREA', 'CREATIONDATE',
       'LASTUPDATE', 'NOTES', 'SHAPE_Length', 'SHAPE_Area'],
      dtype='object')

In [25]:
df.dtypes

OBJECTID                int64
FACILITYID              int64
INTID                   int64
SALESFORCEID          float64
SUBTYPEID             float64
NAME                   object
ADDRESS                object
OWNERSHIP              object
TOTALSPACECOUNT       float64
EVSPACECOUNT          float64
ADASPACECOUNT         float64
RESERVEDSPACECOUNT    float64
VALIDATION             object
PARKINGTYPE            object
NUMBEROFLEVELS        float64
PERMITS               float64
BIPLEASE              float64
BIPAREA               float64
CREATIONDATE          float64
LASTUPDATE             object
NOTES                  object
SHAPE_Length          float64
SHAPE_Area            float64
dtype: object

In [26]:
df.isna().sum()

OBJECTID               0
FACILITYID             0
INTID                  0
SALESFORCEID          50
SUBTYPEID             47
NAME                   0
ADDRESS                0
OWNERSHIP              0
TOTALSPACECOUNT        3
EVSPACECOUNT          81
ADASPACECOUNT         81
RESERVEDSPACECOUNT    82
VALIDATION            59
PARKINGTYPE           59
NUMBEROFLEVELS        81
PERMITS                3
BIPLEASE               3
BIPAREA                3
CREATIONDATE          48
LASTUPDATE             0
NOTES                  0
SHAPE_Length           0
SHAPE_Area             0
dtype: int64

In [28]:
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

# Imputing missing values for numerical columns
numerical_columns = ['SALESFORCEID', 'SUBTYPEID', 'TOTALSPACECOUNT', 'EVSPACECOUNT', 'ADASPACECOUNT', 'RESERVEDSPACECOUNT', 'NUMBEROFLEVELS', 'PERMITS', 'BIPLEASE', 'BIPAREA', 'CREATIONDATE', 'SHAPE_Length', 'SHAPE_Area']
numerical_imputer = SimpleImputer(strategy='median')
df[numerical_columns] = numerical_imputer.fit_transform(df[numerical_columns])

# Imputing missing values for categorical columns
categorical_columns = ['NAME', 'ADDRESS', 'OWNERSHIP', 'VALIDATION', 'PARKINGTYPE', 'LASTUPDATE', 'NOTES']
categorical_imputer = SimpleImputer(strategy='most_frequent')
df[categorical_columns] = categorical_imputer.fit_transform(df[categorical_columns])

# Encoding categorical variables
encoder = OneHotEncoder(sparse=False, handle_unknown='ignore')
encoded_columns = pd.DataFrame(encoder.fit_transform(df[categorical_columns]))
encoded_columns.columns = encoder.get_feature_names_out(categorical_columns)

# Drop original categorical columns and concatenate encoded columns
df.drop(categorical_columns, axis=1, inplace=True)
df = pd.concat([df, encoded_columns], axis=1)

# Your dataframe is now ready for modeling

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [29]:
df.isna().sum()

OBJECTID                             0
FACILITYID                           0
INTID                                0
SALESFORCEID                         0
SUBTYPEID                            0
                                    ..
LASTUPDATE_2021/06/23 00:08:36+00    0
LASTUPDATE_2021/06/23 00:08:37+00    0
LASTUPDATE_2023/10/02 19:27:04+00    0
LASTUPDATE_2023/10/04 03:58:35+00    0
NOTES_none                           0
Length: 189, dtype: int64

In [31]:
df.dtypes

OBJECTID                               int64
FACILITYID                             int64
INTID                                  int64
SALESFORCEID                         float64
SUBTYPEID                            float64
                                      ...
LASTUPDATE_2021/06/23 00:08:36+00    float64
LASTUPDATE_2021/06/23 00:08:37+00    float64
LASTUPDATE_2023/10/02 19:27:04+00    float64
LASTUPDATE_2023/10/04 03:58:35+00    float64
NOTES_none                           float64
Length: 189, dtype: object

In [34]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

X = df.drop('TOTALSPACECOUNT', axis=1)
y = df['TOTALSPACECOUNT']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize models
models = {
    "Linear Regression": LinearRegression(),
    "Random Forest": RandomForestRegressor(),
    "Gradient Boosting": GradientBoostingRegressor()
}

# Function to evaluate models
def evaluate_model(model, X_test, y_test):
    predictions = model.predict(X_test)
    mae = mean_absolute_error(y_test, predictions)
    mse = mean_squared_error(y_test, predictions)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_test, predictions)
    return mae, mse, rmse, r2

# Train and evaluate each model
results = {}
for name, model in models.items():
    model.fit(X_train, y_train)
    results[name] = evaluate_model(model, X_test, y_test)

# Display results
for name, metrics in results.items():
    print(f"{name} - MAE: {metrics[0]}, MSE: {metrics[1]}, RMSE: {metrics[2]}, R^2: {metrics[3]}")

Linear Regression - MAE: 813.9716261186712, MSE: 1538322.995659818, RMSE: 1240.2914962458697, R^2: -4.242694465109046
Random Forest - MAE: 246.43888888888893, MSE: 147218.01587777777, RMSE: 383.6899997104144, R^2: 0.49827241796140986
Gradient Boosting - MAE: 231.305679885264, MSE: 130484.51284114331, RMSE: 361.22640108544573, R^2: 0.5553011720004277